server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Such that hystrix.stream is exposed
management.endpoints.web.exposure.include: '*'
management.endpoints.web.base-path: /

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 4
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000