DROP SEQUENCE IF EXISTS driver_seq;
CREATE SEQUENCE driver_seq START 1;

DROP SEQUENCE IF EXISTS rider_seq;
CREATE SEQUENCE rider_seq START 1;

DROP SEQUENCE IF EXISTS trip_seq;
CREATE SEQUENCE trip_seq START 1;

DROP SEQUENCE IF EXISTS order_seq;
CREATE SEQUENCE order_seq START 1;