server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carhailingdb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true